Repository wri/fti_api, pull requests merged in 2022-11, with the labels that each got.

#358 feature(Documents): Expire non required documents
  app/admin/required_gov_document.rb
  app/models/gov_document.rb
  app/models/operator_document.rb
  app/models/required_gov_document_group.rb
  lib/tasks/scheduler.rake
  spec/factories/gov_documents.rb
  spec/factories/operator_documents.rb
  spec/factories/required_gov_document_groups.rb
  spec/factories/required_gov_documents.rb
  spec/models/gov_document_spec.rb
  spec/models/operator_document_spec.rb
Labels: Code Review Requested

#364 Chore/cleanup jsonapi
  app/controllers/v1/users_controller.rb
  app/resources/v1/about_page_entry_resource.rb
  app/resources/v1/base_resource.rb
  app/resources/v1/category_resource.rb
  app/resources/v1/comment_resource.rb
  app/resources/v1/country_link_resource.rb
  app/resources/v1/country_resource.rb
  app/resources/v1/country_vpa_resource.rb
  app/resources/v1/donor_resource.rb
  app/resources/v1/faq_resource.rb
  app/resources/v1/fmu_resource.rb
  app/resources/v1/gov_document_resource.rb
  app/resources/v1/gov_file_resource.rb
  app/resources/v1/government_resource.rb
  app/resources/v1/how_to_resource.rb
  app/resources/v1/law_resource.rb
  app/resources/v1/notification_resource.rb
  app/resources/v1/observation_document_resource.rb
  app/resources/v1/observation_report_resource.rb
  app/resources/v1/observation_resource.rb
  app/resources/v1/observer_observation_resource.rb
  app/resources/v1/observer_resource.rb
  app/resources/v1/operator_document_annex_resource.rb
  app/resources/v1/operator_document_country_history_resource.rb
  app/resources/v1/operator_document_country_resource.rb
  app/resources/v1/operator_document_fmu_history_resource.rb
  app/resources/v1/operator_document_fmu_resource.rb
  app/resources/v1/operator_document_history_resource.rb
  app/resources/v1/operator_document_resource.rb
  app/resources/v1/operator_resource.rb
  app/resources/v1/partner_resource.rb
  app/resources/v1/required_gov_document_group_resource.rb
  app/resources/v1/required_gov_document_resource.rb
  app/resources/v1/required_operator_document_country_resource.rb
  app/resources/v1/required_operator_document_fmu_resource.rb
  app/resources/v1/required_operator_document_group_resource.rb
  app/resources/v1/required_operator_document_resource.rb
  app/resources/v1/sawmill_resource.rb
  app/resources/v1/score_operator_document_resource.rb
  app/resources/v1/severity_resource.rb
  app/resources/v1/species_resource.rb
  app/resources/v1/subcategory_resource.rb
  app/resources/v1/tool_resource.rb
  app/resources/v1/tutorial_resource.rb
  app/resources/v1/user_permission_resource.rb
  app/resources/v1/user_resource.rb
  config/routes.rb
  spec/integration/v1/categories_spec.rb
  spec/integration/v1/countries_spec.rb
  spec/integration/v1/observers_spec.rb
  spec/integration/v1/species_spec.rb
  spec/integration/v1/subcategories_spec.rb
  spec/integration/v1/users_spec.rb
Labels: Code Review Passed

#361 importer(Documents): Import Generic Operator Documents
  app/admin/operator_document.rb
  app/admin/operator_document_history.rb
  app/models/country.rb
  app/models/operator.rb
  app/models/required_operator_document.rb
  app/models/required_operator_document_country.rb
  app/models/required_operator_document_fmu.rb
  db/files/generic operator documents.csv
  lib/tasks/data_import.rake
  spec/integration/v1/operator_documents_filter_by_country_spec.rb
  spec/integration/v1/operator_documents_spec.rb
  spec/models/operator_document_country_spec.rb
  spec/models/required_operator_document_country_spec.rb
  spec/models/required_operator_document_spec.rb
Labels: Code Review Requested

#337 feature(Newsletter): Send quarterly newsletters to users
  app/helpers/number_helper.rb
  app/models/score_operator_document.rb
  app/services/mail_service.rb
  lib/tasks/scheduler.rake
Labels: Code Review Requested

#369 Fix saving operator document annexes
  app/models/operator_document_annex.rb
  spec/factories/operator_document_annexes.rb
  spec/integration/shared_examples/jsonapi_resources/create.rb
  spec/integration/shared_examples/jsonapi_resources/delete.rb
  spec/integration/shared_examples/jsonapi_resources/edit.rb
  spec/integration/v1/operator_document_annexes_spec.rb
Labels: bug, Code Review Requested

#366 Feature/operator without fmus filter
  app/admin/operator.rb
Labels: Code Review Requested

#365 Fix redirect back in admin panel
  app/admin/observation_document.rb
  app/admin/observation_report.rb
  app/admin/operator.rb
  spec/controllers/admin/observation_documents_controller_spec.rb
  spec/controllers/admin/observation_reports_controller_spec.rb
  spec/controllers/admin/operators_controller_spec.rb
Labels: bug, Code Review Requested
